---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: devops-toolkit-staging
  namespace: flux-system
spec:
  chart:
    spec:
      chart: spring-boot-docker
      sourceRef:
        kind: HelmRepository
        name: acr
  interval: 35s
  targetNamespace: staging
  values:
    image:
      tag: 0.1.2
